"""
Reads one dashboard's config.yaml and scaffolds its dbt staging model, mart models,
sources.yml, a local-dev seed, and schema.yml — written into that same dashboard's
folder, under dbt/staging/, dbt/marts/, and dbt/seeds/. This is the "without much
coding" part for the dbt layer: column casting, model structure, source wiring,
and test stubs are generated; dashboard-specific business logic is left for a
human to fill in - as a TODO in the queue mart (flagged needs_clarification in the
config), as a fully editable default in the summary mart (since every dashboard's
chart aggregation is different), and as actual sample rows in the seed CSV (the
generator can't invent business data, so it only writes the header row).

Every report is fully self-contained under backend/dashboards/<service_id>/<report_id>/
(a "service" like ldc or dlq is just the folder grouping one or more reports -
see core/config_schema.py's module docstring):
    dashboards/<service_id>/<report_id>/config.yaml                            <- you write this
    dashboards/<service_id>/<report_id>/dbt/staging/*.sql                       <- this script writes these
    dashboards/<service_id>/<report_id>/dbt/staging/sources_<dashboard_id>.yml   <- and this
    dashboards/<service_id>/<report_id>/dbt/marts/*.sql                          <- this script writes these
    dashboards/<service_id>/<report_id>/dbt/marts/schema_<dashboard_id>.yml      <- and this
    dashboards/<service_id>/<report_id>/dbt/seeds/seed_<dashboard_id>_raw.csv    <- header only; fill in sample rows by hand

Generated filenames are still keyed by dashboard_id, not report_id - dashboard_id
was already the framework's unique-per-report identifier before the service/
report folder split, so reusing it here means no generated file had to be
renamed when that split was introduced.

The generated sources.yml resolves the same {{ source(...) }} reference used by
the staging model to two different physical tables depending on dbt target: the
duckdb target (local dev) points at the seed CSV above, so `dbt seed && dbt run`
works today with zero real source data; the athena target (CI/prod) points at
this report's real source.database/source.table from config.yaml, which may
still be a TBD_* placeholder pending the source data team. See
backend/dbt_project/ for the project-level dbt_project.yml and profiles.yml that
tie every report's generated models together (model-paths/seed-paths both
point at ../dashboards, so nothing dbt-related needs to live outside each
report's own folder except that one shared project file pair).

Usage:
    python scripts/generate_dbt_models.py dashboards/<service_id>/<report_id>/config.yaml
"""
import sys
from pathlib import Path
import yaml


def _header(config_filename: str) -> str:
    return (
        f"-- AUTO-GENERATED by scripts/generate_dbt_models.py from {config_filename}\n"
        f"-- Re-run the generator after editing the config rather than hand-editing this file,\n"
        f"-- except inside the TODO blocks below, which need dashboard-specific business logic.\n\n"
    )


def build_staging_sql(cfg: dict, config_filename: str) -> str:
    cols = cfg["staging"]["columns"]
    lines = [f"    CAST({c['source_col']} AS {c['type'].upper()}) AS {c['name']}" for c in cols]
    body = ",\n".join(lines)
    src = cfg["source"]
    return (
        _header(config_filename)
        + f"SELECT\n{body}\nFROM {{{{ source('{src['database']}', '{src['table']}') }}}}\n"
    )


def build_mart_queue_sql(cfg: dict, config_filename: str) -> str:
    stg = cfg["staging"]["model_name"]
    col_names = [c["name"] for c in cfg["staging"]["columns"]]
    select_cols = ",\n".join(f"    {c}" for c in col_names)

    todo_lines = []
    for dc in cfg["mart"].get("derived_columns", []):
        tag = "TODO (NEEDS CLARIFICATION)" if dc.get("needs_clarification") else "TODO"
        note = dc.get("note", "")
        todo_lines.append(f"    , NULL AS {dc['name']}  -- {tag}: {note}")
    todo_block = ("\n".join(todo_lines) + "\n") if todo_lines else ""

    return (
        _header(config_filename)
        + f"SELECT\n{select_cols}\n{todo_block}FROM {{{{ ref('{stg}') }}}}\n"
        + f"ORDER BY {cfg['mart']['primary_key']}\n"
    )


def build_mart_summary_sql(cfg: dict, config_filename: str) -> str:
    """
    Generates a *default* summary mart: a zero-filled count of status_field,
    good enough for a simple bar/pie "how many requests in each status" chart.

    This default is a starting point, not the final word. Unlike staging/queue
    models, the summary mart is meant to be hand-edited per dashboard: a
    different dashboard's summary chart might be a sum-by-category, a trend
    over time, or a multi-series rollup, and that logic belongs only here, in
    SQL - never in the API layer, which just does SELECT * FROM this model.
    Re-running the generator overwrites hand edits, same caveat as the TODO
    blocks in mart_<id>_queue.sql.

    Caller must check cfg["mart"].get("summary_model_name") is set before
    calling this - dashboards with api.summary_enabled: false (and therefore
    no summary_model_name) skip this entirely, see main() below.
    """
    stg = cfg["staging"]["model_name"]
    status_field = cfg["mart"]["status_field"]
    status_values = cfg["mart"].get("status_values", [])

    note = (
        "-- DEFAULT CHART LOGIC - EDIT FREELY.\n"
        "-- This is a generated starting point, not generator-protected output. The\n"
        "-- query below is this dashboard's entire summary-chart business logic: the\n"
        "-- API only does `SELECT * FROM` this model and returns the rows as-is, so\n"
        "-- whatever shape/aggregation this dashboard's chart needs (status counts,\n"
        "-- sums by category, a trend line, ...) is written here, once, in SQL - not\n"
        "-- in Python. Re-running the generator WILL overwrite any edits you make\n"
        "-- below; once this file diverges from the default, stop re-running the\n"
        "-- generator for this dashboard's summary mart.\n\n"
    )

    if status_values:
        values_rows = ",\n        ".join(f"('{v}')" for v in status_values)
        body = (
            f"with counts as (\n"
            f"    select\n        {status_field},\n        count(*) as request_count\n"
            f"    from {{{{ ref('{stg}') }}}}\n    group by {status_field}\n),\n"
            f"all_statuses as (\n"
            f"    select {status_field}\n"
            f"    from (values\n        {values_rows}\n    ) as t({status_field})\n)\n"
            f"select\n"
            f"    s.{status_field},\n"
            f"    coalesce(c.request_count, 0) as request_count\n"
            f"from all_statuses s\n"
            f"left join counts c using ({status_field})\n"
            f"order by s.{status_field}\n"
        )
    else:
        body = (
            f"select\n    {status_field},\n    count(*) as request_count\n"
            f"from {{{{ ref('{stg}') }}}}\ngroup by {status_field}\n"
        )

    return _header(config_filename) + note + body


def build_sources_yml(cfg: dict, config_filename: str) -> str:
    """
    Generates this dashboard's sources.yml: defines the source the staging model
    already references via {{ source(database, table) }}, resolved to two
    different physical tables depending on dbt target -

      - duckdb (local dev): the seed CSV this same generator scaffolds at
        dbt/seeds/seed_<dashboard_id>_raw.csv, loaded by `dbt seed` into a table
        of the same name. This makes `dbt seed && dbt run` work today, with zero
        real source data.
      - athena (CI/prod): the real source.database/source.table from this
        dashboard's config.yaml - may still be a TBD_* placeholder pending the
        source data team, same convention as everywhere else in this dashboard's
        generated files.

    Re-running the generator overwrites this file unconditionally, same caveat
    as schema_<dashboard_id>.yml - if the real source names land, update
    config.yaml first, then re-run the generator rather than hand-editing this.
    """
    src = cfg["source"]
    dash_id = cfg["dashboard_id"]
    seed_identifier = f"seed_{dash_id}_raw"
    schema_jinja = "{{ 'main' if target.name == 'duckdb' else '%s' }}" % src["database"]
    identifier_jinja = "{{ '%s' if target.name == 'duckdb' else '%s' }}" % (seed_identifier, src["table"])

    return (
        f"# AUTO-GENERATED by scripts/generate_dbt_models.py from {config_filename}\n"
        f"# Resolves {{{{ source('{src['database']}', '{src['table']}') }}}} (used by the staging\n"
        f"# model) to two different tables depending on dbt target:\n"
        f"#   - duckdb (local dev) -> dbt/seeds/{seed_identifier}.csv, loaded via `dbt seed`\n"
        f"#   - athena (CI/prod)   -> the real source.database/source.table in config.yaml,\n"
        f"#                          confirm with the source data team before relying on it\n"
        f"version: 2\n"
        f"sources:\n"
        f"  - name: {src['database']}\n"
        f"    schema: \"{schema_jinja}\"\n"
        f"    tables:\n"
        f"      - name: {src['table']}\n"
        f"        identifier: \"{identifier_jinja}\"\n"
    )


def build_seed_csv(cfg: dict, config_filename: str) -> str:
    """
    Generates this dashboard's local-dev seed: a header-only CSV using the same
    raw source_col names the staging model casts from (not the renamed staging
    column names). `dbt seed` loads this into a real table named
    seed_<dashboard_id>_raw, which sources.yml points the duckdb target at - the
    thing that actually lets `dbt seed && dbt run` work locally with zero real
    source data.

    The generator only writes the header row; it can't invent business data.
    Fill in sample rows by hand after generating. Re-running the generator WILL
    overwrite this file unconditionally (no read-back, no merge), the same
    caveat as every other generated file here - back up hand-added rows first,
    or stop re-running the generator for this dashboard's seed once it has real
    sample data in it.
    """
    header = ",".join(c["source_col"] for c in cfg["staging"]["columns"])
    return header + "\n"


def build_schema_yml(cfg: dict, config_filename: str) -> str:
    pk = cfg["mart"]["primary_key"]
    status_field = cfg["mart"].get("status_field")
    status_values = cfg["mart"].get("status_values", [])
    queue_model = cfg["mart"]["queue_model_name"]
    summary_model = cfg["mart"].get("summary_model_name")
    values_yaml = "\n".join(f'                - "{v}"' for v in status_values)

    staging_col_names = [c["name"] for c in cfg["staging"]["columns"]]
    derived_cols = cfg["mart"].get("derived_columns", [])

    column_blocks = []
    for name in staging_col_names:
        if name == pk:
            column_blocks.append(f"      - name: {pk}\n        tests: [not_null, unique]")
        elif status_field and name == status_field:
            column_blocks.append(
                f"      - name: {status_field}\n"
                f"        tests:\n"
                f"          - accepted_values:\n"
                f"              values:\n"
                f"{values_yaml}"
            )
        else:
            column_blocks.append(f"      - name: {name}")
    for dc in derived_cols:
        note = dc.get("note", "")
        suffix = f"  # NEEDS CLARIFICATION: {note}" if dc.get("needs_clarification") else ""
        column_blocks.append(f"      - name: {dc['name']}{suffix}")
    columns_yaml = "\n".join(column_blocks)

    out = f"""# AUTO-GENERATED by scripts/generate_dbt_models.py from {config_filename}
version: 2
models:
  - name: {queue_model}
    description: "{cfg['display_name']} — one row per {pk}."
    columns:
{columns_yaml}
"""
    # Summary model block only exists if this dashboard has summary_model_name set
    # (api.summary_enabled: true). Dashboards without a summary chart (e.g. a plain
    # filterable export table) skip this block entirely.
    if summary_model:
        out += f"""  - name: {summary_model}
    description: "{cfg['display_name']} — summary chart data. Default is zero-filled status counts; this dashboard may have hand-edited the SQL for a different aggregation."
    columns:
      - name: {status_field}
      - name: request_count
"""
    return out


def main(config_path: str):
    cfg_path = Path(config_path)
    cfg = yaml.safe_load(cfg_path.read_text())
    config_filename = str(cfg_path)

    # Output lands inside the same report folder the config came from -
    # dashboards/<service_id>/<report_id>/dbt/{staging,marts,seeds}/ - so one
    # report = one self-contained folder with nothing written anywhere else in
    # the repo, except the shared dbt_project.yml/profiles.yml pair under
    # backend/dbt_project/. This is just cfg_path.parent regardless of how
    # deep that path is nested, so it didn't need to change when the
    # service/report folder split was introduced.
    dashboard_dir = cfg_path.parent
    staging_dir = dashboard_dir / "dbt" / "staging"
    marts_dir = dashboard_dir / "dbt" / "marts"
    seeds_dir = dashboard_dir / "dbt" / "seeds"
    staging_dir.mkdir(parents=True, exist_ok=True)
    marts_dir.mkdir(parents=True, exist_ok=True)
    seeds_dir.mkdir(parents=True, exist_ok=True)

    dash_id = cfg["dashboard_id"]
    seed_path = seeds_dir / f"seed_{dash_id}_raw.csv"
    seed_existed = seed_path.exists()

    (staging_dir / f"{cfg['staging']['model_name']}.sql").write_text(build_staging_sql(cfg, config_filename))
    (staging_dir / f"sources_{dash_id}.yml").write_text(build_sources_yml(cfg, config_filename))
    (marts_dir / f"{cfg['mart']['queue_model_name']}.sql").write_text(build_mart_queue_sql(cfg, config_filename))

    # Summary mart is only generated if this dashboard configured one - dashboards
    # with api.summary_enabled: false (no mart.summary_model_name) skip it, matching
    # config_schema.py's validator that only requires summary_model_name when enabled.
    summary_model_name = cfg["mart"].get("summary_model_name")
    if summary_model_name:
        (marts_dir / f"{summary_model_name}.sql").write_text(build_mart_summary_sql(cfg, config_filename))

    (marts_dir / f"schema_{dash_id}.yml").write_text(build_schema_yml(cfg, config_filename))
    seed_path.write_text(build_seed_csv(cfg, config_filename))

    print(f"Generated dbt models for '{dash_id}' in {dashboard_dir / 'dbt'}")
    if not summary_model_name:
        print("  -> no summary_model_name configured - skipped generating a summary mart (summary chart disabled).")
    todo_count = sum(1 for dc in cfg["mart"].get("derived_columns", []) if dc.get("needs_clarification"))
    if todo_count:
        print(f"  -> {todo_count} derived column(s) need business-rule clarification before this mart is complete.")
    if seed_existed:
        print(f"  -> {seed_path} already existed and was OVERWRITTEN (header only) - restore any hand-added sample rows.")
    else:
        print(f"  -> {seed_path} is header-only - add sample rows by hand before `dbt seed` will produce usable local data.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python generate_dbt_models.py dashboards/<service_id>/<report_id>/config.yaml")
        sys.exit(1)
    main(sys.argv[1])
