"""
Reads one dashboard's config.yaml and scaffolds its dbt staging model, mart models,
and schema.yml — written into that same dashboard's folder, under dbt/staging/ and
dbt/marts/. This is the "without much coding" part for the dbt layer: column
casting, model structure, and test stubs are generated; dashboard-specific
business logic is left for a human to fill in - as a TODO in the queue mart
(flagged needs_clarification in the config), and as a fully editable default
in the summary mart, since every dashboard's chart aggregation is different.

Every dashboard is fully self-contained under backend/dashboards/<dashboard_id>/:
    dashboards/<dashboard_id>/config.yaml          <- you write this
    dashboards/<dashboard_id>/dbt/staging/*.sql     <- this script writes these
    dashboards/<dashboard_id>/dbt/marts/*.sql       <- this script writes these
    dashboards/<dashboard_id>/dbt/marts/schema_<dashboard_id>.yml   <- and this

Usage:
    python scripts/generate_dbt_models.py dashboards/<dashboard_id>/config.yaml
"""
import sys
from pathlib import Path
import yaml


def _header(config_filename: str) -> str:
    return (
        f"-- AUTO-GENERATED by scripts/generate_dbt_models.py from {config_filename}\n"
        f"-- Re-run the generator after editing the config rather than hand-editing this file,\n"
        f"-- except inside the TODO blocks below, which need dashboard-specific business logic.\n\n"
    )


def build_staging_sql(cfg: dict, config_filename: str) -> str:
    cols = cfg["staging"]["columns"]
    lines = [f"    CAST({c['source_col']} AS {c['type'].upper()}) AS {c['name']}" for c in cols]
    body = ",\n".join(lines)
    src = cfg["source"]
    return (
        _header(config_filename)
        + f"SELECT\n{body}\nFROM {{{{ source('{src['database']}', '{src['table']}') }}}}\n"
    )


def build_mart_queue_sql(cfg: dict, config_filename: str) -> str:
    stg = cfg["staging"]["model_name"]
    col_names = [c["name"] for c in cfg["staging"]["columns"]]
    select_cols = ",\n".join(f"    {c}" for c in col_names)

    todo_lines = []
    for dc in cfg["mart"].get("derived_columns", []):
        tag = "TODO (NEEDS CLARIFICATION)" if dc.get("needs_clarification") else "TODO"
        note = dc.get("note", "")
        todo_lines.append(f"    , NULL AS {dc['name']}  -- {tag}: {note}")
    todo_block = ("\n".join(todo_lines) + "\n") if todo_lines else ""

    return (
        _header(config_filename)
        + f"SELECT\n{select_cols}\n{todo_block}FROM {{{{ ref('{stg}') }}}}\n"
        + f"ORDER BY {cfg['mart']['primary_key']}\n"
    )


def build_mart_summary_sql(cfg: dict, config_filename: str) -> str:
    """
    Generates a *default* summary mart: a zero-filled count of status_field,
    good enough for a simple bar/pie "how many requests in each status" chart.

    This default is a starting point, not the final word. Unlike staging/queue
    models, the summary mart is meant to be hand-edited per dashboard: a
    different dashboard's summary chart might be a sum-by-category, a trend
    over time, or a multi-series rollup, and that logic belongs only here, in
    SQL - never in the API layer, which just does SELECT * FROM this model.
    Re-running the generator overwrites hand edits, same caveat as the TODO
    blocks in mart_<id>_queue.sql.
    """
    stg = cfg["staging"]["model_name"]
    status_field = cfg["mart"]["status_field"]
    status_values = cfg["mart"].get("status_values", [])

    note = (
        "-- DEFAULT CHART LOGIC - EDIT FREELY.\n"
        "-- This is a generated starting point, not generator-protected output. The\n"
        "-- query below is this dashboard's entire summary-chart business logic: the\n"
        "-- API only does `SELECT * FROM` this model and returns the rows as-is, so\n"
        "-- whatever shape/aggregation this dashboard's chart needs (status counts,\n"
        "-- sums by category, a trend line, ...) is written here, once, in SQL - not\n"
        "-- in Python. Re-running the generator WILL overwrite any edits you make\n"
        "-- below; once this file diverges from the default, stop re-running the\n"
        "-- generator for this dashboard's summary mart.\n\n"
    )

    if status_values:
        values_rows = ",\n        ".join(f"('{v}')" for v in status_values)
        body = (
            f"with counts as (\n"
            f"    select\n        {status_field},\n        count(*) as request_count\n"
            f"    from {{{{ ref('{stg}') }}}}\n    group by {status_field}\n),\n"
            f"all_statuses as (\n"
            f"    select column1 as {status_field}\n"
            f"    from (values\n        {values_rows}\n    ) as t\n)\n"
            f"select\n"
            f"    s.{status_field},\n"
            f"    coalesce(c.request_count, 0) as request_count\n"
            f"from all_statuses s\n"
            f"left join counts c using ({status_field})\n"
            f"order by s.{status_field}\n"
        )
    else:
        body = (
            f"select\n    {status_field},\n    count(*) as request_count\n"
            f"from {{{{ ref('{stg}') }}}}\ngroup by {status_field}\n"
        )

    return _header(config_filename) + note + body


def build_schema_yml(cfg: dict, config_filename: str) -> str:
    pk = cfg["mart"]["primary_key"]
    status_field = cfg["mart"]["status_field"]
    status_values = cfg["mart"].get("status_values", [])
    queue_model = cfg["mart"]["queue_model_name"]
    summary_model = cfg["mart"]["summary_model_name"]
    values_yaml = "\n".join(f'                - "{v}"' for v in status_values)

    staging_col_names = [c["name"] for c in cfg["staging"]["columns"]]
    derived_cols = cfg["mart"].get("derived_columns", [])

    column_blocks = []
    for name in staging_col_names:
        if name == pk:
            column_blocks.append(f"      - name: {pk}\n        tests: [not_null, unique]")
        elif name == status_field:
            column_blocks.append(
                f"      - name: {status_field}\n"
                f"        tests:\n"
                f"          - accepted_values:\n"
                f"              values:\n"
                f"{values_yaml}"
            )
        else:
            column_blocks.append(f"      - name: {name}")
    for dc in derived_cols:
        note = dc.get("note", "")
        suffix = f"  # NEEDS CLARIFICATION: {note}" if dc.get("needs_clarification") else ""
        column_blocks.append(f"      - name: {dc['name']}{suffix}")
    columns_yaml = "\n".join(column_blocks)

    return f"""# AUTO-GENERATED by scripts/generate_dbt_models.py from {config_filename}
version: 2
models:
  - name: {queue_model}
    description: "{cfg['display_name']} \u2014 one row per {pk}."
    columns:
{columns_yaml}
  - name: {summary_model}
    description: "{cfg['display_name']} \u2014 summary chart data. Default is zero-filled status counts; this dashboard may have hand-edited the SQL for a different aggregation."
    columns:
      - name: {status_field}
      - name: request_count
"""


def main(config_path: str):
    cfg_path = Path(config_path)
    cfg = yaml.safe_load(cfg_path.read_text())
    config_filename = str(cfg_path)

    # Output lands inside the same dashboard folder the config came from -
    # dashboards/<dashboard_id>/dbt/{staging,marts}/ - so one dashboard = one
    # self-contained folder with nothing written anywhere else in the repo.
    dashboard_dir = cfg_path.parent
    staging_dir = dashboard_dir / "dbt" / "staging"
    marts_dir = dashboard_dir / "dbt" / "marts"
    staging_dir.mkdir(parents=True, exist_ok=True)
    marts_dir.mkdir(parents=True, exist_ok=True)

    (staging_dir / f"{cfg['staging']['model_name']}.sql").write_text(build_staging_sql(cfg, config_filename))
    (marts_dir / f"{cfg['mart']['queue_model_name']}.sql").write_text(build_mart_queue_sql(cfg, config_filename))
    (marts_dir / f"{cfg['mart']['summary_model_name']}.sql").write_text(build_mart_summary_sql(cfg, config_filename))
    (marts_dir / f"schema_{cfg['dashboard_id']}.yml").write_text(build_schema_yml(cfg, config_filename))

    print(f"Generated dbt models for '{cfg['dashboard_id']}' in {dashboard_dir / 'dbt'}")
    todo_count = sum(1 for dc in cfg["mart"].get("derived_columns", []) if dc.get("needs_clarification"))
    if todo_count:
        print(f"  -> {todo_count} derived column(s) need business-rule clarification before this mart is complete.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python generate_dbt_models.py dashboards/<dashboard_id>/config.yaml")
        sys.exit(1)
    main(sys.argv[1])
