-- AUTO-GENERATED by scripts/generate_dbt_models.py from dashboards/ldc/config.yaml
-- Re-run the generator after editing the config rather than hand-editing this file,
-- except inside the TODO blocks below, which need dashboard-specific business logic.

-- DEFAULT CHART LOGIC - EDIT FREELY.
-- This is a generated starting point, not generator-protected output. The
-- query below is this dashboard's entire summary-chart business logic: the
-- API only does `SELECT * FROM` this model and returns the rows as-is, so
-- whatever shape/aggregation this dashboard's chart needs (status counts,
-- sums by category, a trend line, ...) is written here, once, in SQL - not
-- in Python. Re-running the generator WILL overwrite any edits you make
-- below; once this file diverges from the default, stop re-running the
-- generator for this dashboard's summary mart.

with counts as (
    select
        request_status,
        count(*) as request_count
    from {{ ref('stg_ldc_case_requests') }}
    group by request_status
),
all_statuses as (
    select request_status
    from (values
        ('Draft'),
        ('Exception Review'),
        ('Pending Reclass'),
        ('Completed'),
        ('Canceled'),
        ('Rejected')
    ) as t(request_status)
)
select
    s.request_status,
    coalesce(c.request_count, 0) as request_count
from all_statuses s
left join counts c using (request_status)
order by s.request_status
