-- AUTO-GENERATED by scripts/generate_dbt_models.py from dashboards/dlq/config.yaml
-- Re-run the generator after editing the config rather than hand-editing this file,
-- except inside the TODO blocks below, which need dashboard-specific business logic.

SELECT
    CAST(fnm_loan_number AS VARCHAR) AS fnm_loan_number,
    CAST(servicer_loan_identifier AS VARCHAR) AS servicer_loan_identifier,
    CAST(master_servicer_number AS VARCHAR) AS master_servicer_number,
    CAST(master_servicer_name AS VARCHAR) AS master_servicer_name,
    CAST(acting_servicer_number AS VARCHAR) AS acting_servicer_number,
    CAST(acting_servicer_name AS VARCHAR) AS acting_servicer_name,
    CAST(activity_period AS VARCHAR) AS activity_period,
    CAST(periods_delinquent AS INTEGER) AS periods_delinquent,
    CAST(servicer_action_type AS VARCHAR) AS servicer_action_type,
    CAST(servicer_action_type_received_dt AS DATE) AS servicer_action_type_received_dt,
    CAST(conditional_data_attributes_action_type AS VARCHAR) AS conditional_data_attributes_action_type,
    CAST(delinquency_status_type_received_date AS DATE) AS delinquency_status_type_received_date,
    CAST(delinquency_status_type_1 AS VARCHAR) AS delinquency_status_type_1,
    CAST(delinquency_status_type_2 AS VARCHAR) AS delinquency_status_type_2,
    CAST(delinquency_status_type_3 AS VARCHAR) AS delinquency_status_type_3,
    CAST(delinquency_status_type_4 AS VARCHAR) AS delinquency_status_type_4,
    CAST(delinquency_status_type_5 AS VARCHAR) AS delinquency_status_type_5,
    CAST(delinquency_reason_type_received_date AS DATE) AS delinquency_reason_type_received_date,
    CAST(delinquency_reason_type_1 AS VARCHAR) AS delinquency_reason_type_1,
    CAST(delinquency_reason_type_2 AS VARCHAR) AS delinquency_reason_type_2,
    CAST(delinquency_reason_type_3 AS VARCHAR) AS delinquency_reason_type_3,
    CAST(delinquency_reason_type_4 AS VARCHAR) AS delinquency_reason_type_4,
    CAST(delinquency_reason_type_5 AS VARCHAR) AS delinquency_reason_type_5
FROM {{ source('TBD_source_database', 'TBD_dlq_reported_data') }}
