-- AUTO-GENERATED by scripts/generate_dbt_models.py from dashboards/ldc/config.yaml
-- Re-run the generator after editing the config rather than hand-editing this file,
-- except inside the TODO blocks below, which need dashboard-specific business logic.

SELECT
    request_no,
    request_status,
    sub_status,
    submitter_name,
    submitter_group,
    seller_number,
    seller_name,
    servicer_number,
    servicer_name,
    reviewer_group,
    reviewer_name,
    fm_loan_number,
    submission_date,
    completion_date,
    loan_count,
    attribute_count
    , NULL AS queue_age  -- TODO (NEEDS CLARIFICATION): Elapsed-time calc TBD - calendar vs business hours
    , NULL AS cycle_time  -- TODO (NEEDS CLARIFICATION): Business-day calc TBD; only meaningful once Completion Date is set
    , NULL AS sla_status  -- TODO (NEEDS CLARIFICATION): SLA thresholds (Within SLA / At Risk / Breached) TBD
FROM {{ ref('stg_ldc_case_requests') }}
ORDER BY request_no
