-- AUTO-GENERATED by scripts/generate_dbt_models.py from dashboards/ldc/config.yaml
-- Re-run the generator after editing the config rather than hand-editing this file,
-- except inside the TODO blocks below, which need dashboard-specific business logic.

SELECT
    CAST(request_no AS VARCHAR) AS request_no,
    CAST(status AS VARCHAR) AS request_status,
    CAST(sub_status AS VARCHAR) AS sub_status,
    CAST(submitter_name AS VARCHAR) AS submitter_name,
    CAST(submitter_group AS VARCHAR) AS submitter_group,
    CAST(seller_number AS VARCHAR) AS seller_number,
    CAST(seller_name AS VARCHAR) AS seller_name,
    CAST(servicer_number AS VARCHAR) AS servicer_number,
    CAST(servicer_name AS VARCHAR) AS servicer_name,
    CAST(reviewer_group AS VARCHAR) AS reviewer_group,
    CAST(reviewer_name AS VARCHAR) AS reviewer_name,
    CAST(fm_loan_number AS VARCHAR) AS fm_loan_number,
    CAST(submission_date AS DATE) AS submission_date,
    CAST(completion_date AS DATE) AS completion_date,
    CAST(loan_count AS INTEGER) AS loan_count,
    CAST(attribute_count AS INTEGER) AS attribute_count
FROM {{ source('TBD_source_database', 'TBD_ldc_case_requests') }}
