-- AUTO-GENERATED by scripts/generate_dbt_models.py from dashboards/dlq/config.yaml,
-- then HAND-EDITED to add the trailing-24-month window below (project decision -
-- see conversation: implement as a straightforward WHERE filter, not flagged
-- needs_clarification). Re-running the generator will overwrite this file and
-- silently drop the WHERE/CTE below back to a plain SELECT * - re-apply this
-- edit (or stop re-running the generator for this dashboard) if you regenerate.
--
-- Window definition: the trailing 24 calendar months ending at (and including)
-- the latest activity_period present in the staged data - NOT 24 months back
-- from today's wall-clock date, since this is snapshot_eom batch data that may
-- lag behind the current date. activity_period is staged as "MM/YYYY" text and
-- parsed here for the comparison only; the output column stays the original text.

WITH bounds AS (
    SELECT MAX(strptime(activity_period, '%m/%Y')) AS latest_period
    FROM {{ ref('stg_dlq_reported_data') }}
)
SELECT
    s.fnm_loan_number,
    s.servicer_loan_identifier,
    s.master_servicer_number,
    s.master_servicer_name,
    s.acting_servicer_number,
    s.acting_servicer_name,
    s.activity_period,
    s.periods_delinquent,
    s.servicer_action_type,
    s.servicer_action_type_received_dt,
    s.conditional_data_attributes_action_type,
    s.delinquency_status_type_received_date,
    s.delinquency_status_type_1,
    s.delinquency_status_type_2,
    s.delinquency_status_type_3,
    s.delinquency_status_type_4,
    s.delinquency_status_type_5,
    s.delinquency_reason_type_received_date,
    s.delinquency_reason_type_1,
    s.delinquency_reason_type_2,
    s.delinquency_reason_type_3,
    s.delinquency_reason_type_4,
    s.delinquency_reason_type_5
FROM {{ ref('stg_dlq_reported_data') }} s
CROSS JOIN bounds b
WHERE strptime(s.activity_period, '%m/%Y') >= date_trunc('month', b.latest_period) - INTERVAL '23 months'
ORDER BY s.fnm_loan_number
